"""SQLite-backed coordination repository API."""

from .storage import (  # noqa: F401
    acquire_background_lease,
    acquire_background_slot,
    acquire_sse_slot,
    claim_next_gallery_job,
    cleanup_expired_gallery_jobs,
    cleanup_stale_gallery_jobs,
    complete_background_lease,
    count_active_gallery_jobs,
    count_active_sse_slots,
    create_gallery_job,
    delete_gallery_job,
    get_gallery_job,
    get_gallery_jobs_updated_at_edges,
    get_runtime_coordination_metrics,
    list_gallery_job_ids_with_files,
    mark_worker_heartbeat,
    record_worker_metrics_snapshot,
    refresh_sse_slot,
    release_background_lease,
    release_background_slot,
    release_sse_slot,
    reserve_gallery_job_capacity,
    update_gallery_job,
    update_gallery_job_progress,
)
